### PR TITLE
Changed version in gradle compile line

### PR DESCRIPTION
**Pull request by timkoers**

### CODE REVIEW

**Comment by thyrlian** [comment]
Thanks for spotting that mistake out 👍

**Comment by timkoers** [comment]
No problem man! Btw, which version of JUnit are you using? Android Studio gives the error that I am using version 4.12, but your library might be using version 4.11

**Comment by thyrlian** [comment]
Actually I'm using this one as a product flavor, not JUnit is involved.  And it should not have any problem with JUnit 4.12.

**Comment by timkoers** [comment]
That's strange, then something else might be messing things up. Thanks!

**Comment by thyrlian** [comment]
It sounds like something doesn't work with Espresso, I'll write some sample code / tutorial about how to use it together with Espresso later.  Meanwhile maybe you can have a try with the product flavor approach mentioned in README.  Thanks a lot :)

**Comment by timkoers** [comment]
I don't have Espresso compiled, could it still be an issue?
ERROR:
Error:Conflict with dependency 'junit:junit'. Resolved versions for app (4.11) and test app (4.12) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Pull request merged**
